// Mocks generated by Mockito 5.4.0 from annotations
// in activities_app/test/features/activity/data/repository/activity_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:activities_app/core/network/network_info.dart' as _i6;
import 'package:activities_app/features/activity/data/datasources/activity_local_datasource.dart'
    as _i5;
import 'package:activities_app/features/activity/data/datasources/activity_remote_datasource.dart'
    as _i3;
import 'package:activities_app/features/activity/data/models/activity_model.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeActivityModel_0 extends _i1.SmartFake implements _i2.ActivityModel {
  _FakeActivityModel_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ActivityRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockActivityRemoteDataSource extends _i1.Mock
    implements _i3.ActivityRemoteDataSource {
  @override
  _i4.Future<_i2.ActivityModel> getActivity() => (super.noSuchMethod(
        Invocation.method(
          #getActivity,
          [],
        ),
        returnValue: _i4.Future<_i2.ActivityModel>.value(_FakeActivityModel_0(
          this,
          Invocation.method(
            #getActivity,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.ActivityModel>.value(_FakeActivityModel_0(
          this,
          Invocation.method(
            #getActivity,
            [],
          ),
        )),
      ) as _i4.Future<_i2.ActivityModel>);
  @override
  _i4.Future<_i2.ActivityModel> getByType(String? type) => (super.noSuchMethod(
        Invocation.method(
          #getByType,
          [type],
        ),
        returnValue: _i4.Future<_i2.ActivityModel>.value(_FakeActivityModel_0(
          this,
          Invocation.method(
            #getByType,
            [type],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.ActivityModel>.value(_FakeActivityModel_0(
          this,
          Invocation.method(
            #getByType,
            [type],
          ),
        )),
      ) as _i4.Future<_i2.ActivityModel>);
}

/// A class which mocks [ActivityLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockActivityLocalDataSource extends _i1.Mock
    implements _i5.ActivityLocalDataSource {
  @override
  _i4.Future<_i2.ActivityModel> getLastActivity() => (super.noSuchMethod(
        Invocation.method(
          #getLastActivity,
          [],
        ),
        returnValue: _i4.Future<_i2.ActivityModel>.value(_FakeActivityModel_0(
          this,
          Invocation.method(
            #getLastActivity,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.ActivityModel>.value(_FakeActivityModel_0(
          this,
          Invocation.method(
            #getLastActivity,
            [],
          ),
        )),
      ) as _i4.Future<_i2.ActivityModel>);
  @override
  _i4.Future<void> cacheActivity(_i2.ActivityModel? activity) =>
      (super.noSuchMethod(
        Invocation.method(
          #cacheActivity,
          [activity],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [NetworkInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkInfo extends _i1.Mock implements _i6.NetworkInfo {
  @override
  _i4.Future<bool> get isConnected => (super.noSuchMethod(
        Invocation.getter(#isConnected),
        returnValue: _i4.Future<bool>.value(false),
        returnValueForMissingStub: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);
}
